variable "docs_url" {
    description = "Path to Swagger docs generated by FastAPI"
    type        = string
    default     = "/docs"
}

variable "env" {
    description = "The environment to deploy the function to"
    type        = string
    default     = "staging"
}

variable "jwt_hash_algorithm" {
    description = "Hashing Algorithm used for encoding JWT"
    type        = string
    default     = "HS256"
}

variable "jwt_secret_key" {
    description = "Secret Key used for encoding JWT"
    type        = string
}

variable "vpc_tfstate_key" {
    description = "The key to the VPC terraform state file"
    type        = string
    default     = "vpc/staging/terraform.tfstate"
}

variable "eventbridge_tfstate_key" {
    description = "The key to the EventBridge terraform state file"
    type        = string
    default     = "eventbridge/global/terraform.tfstate"
}

variable "rds_tfstate_key" {
    description = "The key to the RDS terraform state file"
    type        = string
    default     = "rds/staging/terraform.tfstate"
}

variable "aws_region" {
    description = "The AWS region to deploy the function to"
    type        = string
    default     = "us-east-1"
}

variable "google_oauth_client_id" {
    description = "Google Client ID for OAuth"
    type        = string
}

variable "google_oauth_client_secret" {
    description = "Google Client Secret for OAuth"
    type        = string
}

variable "google_oauth_redirect_uri" {
    description = "Google Redirect URI for OAuth"
    type        = string
}

variable "openai_api_key" {
    description = "OpenAI API Key"
    type        = string
}

variable "sentry_dsn" {
    description = "Sentry DSN"
    type        = string
}