/** @type {import('tailwindcss').Config} */

const rem = num => ({ [num]: `${num / 16}rem` });

export default {
  content: [ './index.html', './src/**/*.{ts,tsx}' ],
  theme: {
    extend: {
      colors: {
        monoid: {
          100: '#FEFCFA',
          300: '#F5EEE2',
          500: '#DBDAC1',
          600: '#FAF7F4',
          700: '#8E7B89',
          900: '#6D4D64',
          lime: {
            500: '#BFF0BB',
          },
          green: {
            500: '#64a838',
          },
          orange: {
            500: '#F0D5BB',
          },
          yellow: {
            500: '#F0EBBB',
          },
          purple: {
            500: '#D6BBF0',
          },
          blue: {
            500: '#BBD8F0',
          },
        },
      },
      dropShadow: {
        up: '0 64px 64px rgba(0, 0, 0, 0.75)',
      },
      // spacing: {
      //   px: '1px',
      //   0: '0',
      //   ...rem( 1 ),
      //   ...rem( 2 ),
      //   ...rem( 3 ),
      //   ...rem( 4 ),
      //   ...rem( 5 ),
      //   ...rem( 6 ),
      //   ...rem( 7 ),
      //   ...rem( 8 ),
      //   ...rem( 9 ),
      //   ...rem( 10 ),
      //   ...rem( 11 ),
      //   ...rem( 12 ),
      //   ...rem( 13 ),
      //   ...rem( 14 ),
      //   ...rem( 15 ),
      //   ...rem( 16 ),
      //   ...rem( 17 ),
      //   ...rem( 18 ),
      //   ...rem( 19 ),
      //   ...rem( 20 ),
      //   ...rem( 22 ),
      //   ...rem( 23 ),
      //   ...rem( 24 ),
      //   ...rem( 25 ),
      //   ...rem( 26 ),
      //   ...rem( 28 ),
      //   ...rem( 29 ),
      //   ...rem( 30 ),
      //   ...rem( 32 ),
      //   ...rem( 33 ),
      //   ...rem( 34 ),
      //   ...rem( 35 ),
      //   ...rem( 36 ),
      //   ...rem( 37 ),
      //   ...rem( 38 ),
      //   ...rem( 39 ),
      //   ...rem( 40 ),
      //   ...rem( 44 ),
      //   ...rem( 45 ),
      //   ...rem( 46 ),
      //   ...rem( 48 ),
      //   ...rem( 50 ),
      //   ...rem( 70 ),
      //   ...rem( 75 ),
      //   ...rem( 80 ),
      //   ...rem( 90 ),
      //   ...rem( 92 ),
      //   ...rem( 100 ),
      //   ...rem( 130 ),
      //   ...rem( 140 ),
      //   ...rem( 150 ),
      //   ...rem( 200 ),
      //   ...rem( 250 ),
      //   ...rem( 260 ),
      //   ...rem( 270 ),
      //   ...rem( 280 ),
      //   ...rem( 290 ),
      //   ...rem( 300 ),
      //   ...rem( 320 ),
      //   ...rem( 340 ),
      //   ...rem( 350 ),
      // },
      fontSize: {
        ...rem( 0 ),
        ...rem( 6 ),
        ...rem( 10 ),
        ...rem( 11 ),
        ...rem( 12 ),
        ...rem( 13 ),
        ...rem( 14 ),
        ...rem( 15 ),
        ...rem( 16 ),
        ...rem( 17 ),
        ...rem( 18 ),
        ...rem( 20 ),
        ...rem( 24 ),
        ...rem( 25 ),
        ...rem( 26 ),
        ...rem( 28 ),
        ...rem( 30 ),
      },
      lineHeight: {
        1: 1,
        ...rem( 11 ),
        ...rem( 16 ),
        ...rem( 18 ),
        ...rem( 19 ),
        ...rem( 20 ),
        ...rem( 22 ),
        ...rem( 23 ),
        ...rem( 24 ),
        ...rem( 26 ),
        ...rem( 28 ),
      },
    },
  },
  plugins: [],
};
