variable "jwt_secret_key" {
    description = "Secret Key used for encoding JWT"
    type        = string
}

variable "google_oauth_client_id" {
    description = "Google Client ID for OAuth"
    type        = string
}

variable "google_oauth_client_secret" {
    description = "Google Client Secret for OAuth"
    type        = string
}

variable "google_oauth_redirect_uri" {
    description = "Google Redirect URI for OAuth"
    type        = string
}

variable "openai_api_key" {
    description = "OpenAI API Key"
    type        = string
}

variable "sentry_dsn" {
    description = "Sentry DSN"
    type        = string
}

variable "docs_url" {
    description = "Path to Swagger docs generated by FastAPI"
    type        = string
    default     = "/docs"
}